local MEM = require "modules.memory"
local SET = require "modules.settings"
local SND = require "modules.sound"

function init(self)
	sound.set_group_gain(hash("master"), SET.volume_general)
	sound.set_group_gain(hash("metronome"), SET.volume_metronome)
	sound.set_group_gain(hash("music"), SET.volume_music)
end

local function stop_music()
	if SND.music_is_playing then
		SND.music_is_playing = false
		sound.stop("/sound#music")
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("play_music") and MEM.music then
		stop_music()
		SND.music_is_playing = true
		sound.play("/sound#music", {delay = 0, start_time = message.start or 0})
	elseif message_id == hash("stop_music") then
		stop_music()
	elseif message_id == hash("music_loaded") then
		stop_music()
		go.set("/sound#music", "sound", MEM.music)
		SND.music_loaded = true
	end
end