local MEM = require "modules.memory"
local UI = require "modules.ui"
local G = require "modules.global"
local SET = require "modules.settings"
local MOD = require "modules.models"
local TRANS = require "modules.transform"
local DIALOG = UI.DIALOG
local TAB_NAME = "tab_art"

local model_list, part_list, tween_list, instance_list, evaluate_button, evaluate_input, current_material
local material_buttons = {}
local select_model

local current_tab = "button_materials"
local tab_buttons = {}
local transform_ui_list, tween_ui_list, instance_ui_list
local selected_tween = 0

local material_list = {
	-- default
	"(DoNotEdit)LiveMat_Props",
	"(DoNotEdit)LiveMat_LevelGeoSimple",
	"(DoNotEdit)LiveMat_Glow",
	"(DoNotEdit)LiveMat_GlowInvert",
	--variants of standard
	"(DoNotEdit)LiveMat_Pedestrians_Dissolve",
	"(DoNotEdit)LiveMat_Continental Interior 1",
	"(DoNotEdit)LiveMat_Continental Interior 2",
	"(DoNotEdit)LiveMat_FrontEnd_Building",
	"(DoNotEdit)LiveMat_LevelGeoComplex",
	"(DoNotEdit)LiveMat_Enemies_Targets",
	--white
	"(DoNotEdit)LiveMat_EnemyGlow",
	"(DoNotEdit)LiveMat_EnemyGlow_Gun",
	"(DoNotEdit)LiveMat_ParticleMesh_EnviroColor",
	"(DoNotEdit)LiveMat_ParticleMesh_Glow",
	--black
	"(DoNotEdit)LiveMat_MegaHitTrail",
	"(DoNotEdit)LiveMat_Gunmat New Three Color",
	--transparent
	"(DoNotEdit)LiveMat_Player_MuzzleFlashSquirtgun",
	"(DoNotEdit)LiveMat_Squirtgun_drops",
	-- combinations
	"(DoNotEdit)LiveMat_Obstacles",
	"(DoNotEdit)LiveMat_MRObstacles",
	"(DoNotEdit)LiveMat_Props_NoDistortion",
	"(DoNotEdit)LiveMat_ParticleMesh_GlowMultiply",
	"(DoNotEdit)LiveMat_Pedestrians",
	"(DoNotEdit)LiveMat_PedestriansAlt",
	-- unique
	"(DoNotEdit)LiveMat_Enemies_Shielded",
	"(DoNotEdit)LiveMat_Beatcubes_mat",
	"(DoNotEdit)LiveMat_Enemies_DeadBody",
	-- chaotic
	"(DoNotEdit)LiveMat_Enemies",
	"(DoNotEdit)LiveMat_Boss",
	"(DoNotEdit)LiveMat_PlayerRingOuter2"
}

local material_label_list = {
	[1] = "Default",
	[5] = "Variants on standard",
	[11] = "White",
	[15] = "Black",
	[17] = "Transparent",
	[19] = "Combinations",
	[25] = "Unique",
	[28] = "Chaotic",
}

local function get_selected_model()
	return UI.tab.tab_art.scrolling_lists[model_list].exclusive_button.selected
end

local function get_selected_part()
	return UI.tab.tab_art.scrolling_lists[part_list].exclusive_button.selected
end

function init(self)
	gui.set_render_order(1)
	msg.post("#", hash("disable"))
	UI.load_template({"sort", "button_replace", "button_rename", "button_find", "colour_guide", "import_models", "import_models_bulk",
	"button_materials", "button_transforms", "button_tweens", "button_instances"}, TAB_NAME)
	tab_buttons = {
		button_materials = gui.get_node("button_materials/button_white"),
		button_transforms = gui.get_node("button_transforms/button_white"),
		button_tweens = gui.get_node("button_tweens/button_white"),
		button_instances = gui.get_node("button_instances/button_white")
	}
	gui.set_color(tab_buttons[current_tab], SET.colour_active_text_field)
	gui.set_enabled(gui.get_node("transforms_background"), false)
	gui.set_enabled(gui.get_node("tweens_background"), false)
	gui.set_enabled(gui.get_node("instances_background"), false)
	transform_ui_list = TRANS.init(evaluate_button)
	UI.disable_list(TAB_NAME, transform_ui_list)
	
	local mat_template = gui.get_node("mat_0/button_white")
	local position = gui.get_position(mat_template)
	local start_y = position.y
	local size = gui.get_size(mat_template)
	local mat_background = gui.get_node("materials_background")
	for key, val in ipairs(material_list) do
		if key == 17 then
			position.x = position.x + size.x
			position.y = start_y
		end
		position.y = position.y - size.y
		if material_label_list[key] then
			local new_label = gui.clone(gui.get_node("mat_label_template"))
			gui.set_text(new_label, material_label_list[key])
			gui.set_position(new_label, position)
			gui.set_parent(new_label, mat_background, true)
			position.y = position.y - size.y
		end
		local new = gui.clone_tree(mat_template)
		gui.set_id(new["mat_0/button_white"], "mat_"..key.."/button_white")
		gui.set_id(new["mat_0/text"], "mat_"..key.."/text")
		gui.set_position(new["mat_0/button_white"], position)
		gui.set_text(new["mat_0/text"], string.sub(material_list[key], 20))
		gui.set_parent(new["mat_0/button_white"], mat_background, true)
		--gui.set_color(new["mat_0/button_white"], COL.materials[material_list[key]].tint())
		table.insert(material_buttons, new["mat_0/button_white"])
	end
	gui.delete_node(gui.get_node("mat_0/text"))
	gui.delete_node(mat_template)
	gui.delete_node(gui.get_node("mat_label_template"))

	local function get_tween_colour(tween_index)
		if tween_list[tween_index].collision then
			return SET.colour_tween_collision
		end
		local time = {S = 0, R = 0, T = 0}
		local count = {S = 0, R = 0, T = 0}
		for key, val in ipairs(tween_list[tween_index].script) do
			if time[val.type] then
				time[val.type] = time[val.type] + val.time
				count[val.type] = count[val.type] + 1
			end
		end
		if time.T > time.S and time.T > time.R then
			return SET.colour_tween_move
		elseif time.S > time.R and time.S > time.T then
			return SET.colour_tween_scale
		elseif time.R > time.S and time.R > time.T then
			return SET.colour_tween_rotate
		else
			if count.T > count.S and count.T > count.R then
				return SET.colour_tween_move
			elseif count.S > count.R and count.S > count.T then
				return SET.colour_tween_scale
			elseif count.R > count.S and count.R > count.T then
				return SET.colour_tween_rotate
			end
		end
		return vmath.vector4(1, 1, 1, 1)
	end

	local tween_list_tab = {
		{
			type = hash("exclusive_button"),
			node = gui.get_node("tween_exclusive/button_white"),
			text_node = gui.get_node("tween_exclusive/text"),
			value_fn = function(i)
				return tween_list[i].name.." ("..tween_list[i].signal..")"
			end,
			template = "tween_exclusive;",
			tint = get_tween_colour,
			release_only = true,
			fn = evaluate_button
		},
		item_count = 0,
		scroll_prefix = "tween_list_"
	}
	tween_ui_list = UI.create_list(TAB_NAME, gui.get_node("tween_list"), tween_list_tab)
	UI.disable_list(TAB_NAME, tween_ui_list)

	local function get_range(i)
		local max_distance = math.huge
		if MEM.level_data.songLength then
			max_distance = tonumber(MEM.level_data.songLength) * 3
		end
		local spawn = G.clamp(instance_list[i].spawn_range * 16 - 7, 0, max_distance)
		local despawn = G.clamp(instance_list[i].despawn_range * 16 + 7, 0, max_distance)
		return G.round(spawn / 3, 1).."/"..G.round(despawn / 3, 1)
	end

	local instance_list_tab = {
		{
			type = hash("label"),
			node = gui.get_node("lbl_position_x"),
			value_fn = function(i) return G.round(instance_list[i].position.x, 2) end,
		},
		{
			type = hash("label"),
			node = gui.get_node("lbl_position_y"),
			value_fn = function(i) return G.round(instance_list[i].position.y, 2) end,
		},
		{
			type = hash("label"),
			node = gui.get_node("lbl_position_z"),
			value_fn = function(i) return G.round(instance_list[i].position.z, 2) end,
		},
		{
			type = hash("label"),
			node = gui.get_node("lbl_range"),
			value_fn = get_range,
		},
		{
			type = hash("button"),
			node = gui.get_node("instance_edit/button_white"),
			text_node = gui.get_node("instance_edit/text"),
			value_fn = function() return "" end,
			template = "instance_edit;",
			gfx = hash("button_exclusive")
		},
		{
			type = hash("button"),
			node = gui.get_node("prop_view/button_white"),
			text_node = gui.get_node("prop_view/text"),
			value_fn = function() return "" end,
			template = "prop_view;",
			gfx = hash("button_exclusive"),
			enabled = function() return true end
		},
		{
			type = hash("button"),
			node = gui.get_node("prop_delete/button_white"),
			text_node = gui.get_node("prop_delete/text"),
			value_fn = function() return "" end,
			template = "prop_delete;",
			gfx = hash("button_exclusive")
		},
		{
			type = hash("button"),
			node = gui.get_node("geo/button_white"),
			text_node = gui.get_node("geo/text"),
			value_fn = function() return "GEO" end,
			template = "geo;",
			gfx = hash("button_exclusive")
		},
		item_count = 0,
		scroll_prefix = "instances_list_"
	}

	instance_ui_list = UI.create_list(TAB_NAME, gui.get_node("instances_list"), instance_list_tab)
	UI.disable_list(TAB_NAME, instance_ui_list)

	local model_list_tab = {
		{
			type = hash("button"),
			node = gui.get_node("model_hide/button_white"),
			text_node = gui.get_node("model_hide/text"),
			gfx = hash("button_exclusive"),
			value_flipbook = true,
			value_fn = function(i)
				if MEM.art_data.table.propsDictionary[i].hide then
					return "button_hidden"
				else
					return "button_visibility"
				end
			end,
			template = "model_hide;",
			tint = function(i)
				if MEM.art_data.table.propsDictionary[i].hide then
					return SET.colour_hidden_model
				else
					return vmath.vector4(1, 1, 1, 1)
				end
			end,
		},
		{
			type = hash("button"),
			node = gui.get_node("model_dynamic/button_white"),
			text_node = gui.get_node("model_dynamic/text"),
			gfx = hash("button_exclusive"),
			value_fn = function(i)
				if (MEM.art_data.table.propsDictionary[i].tween or 0) > 0 then
					return "Tween ("..MEM.art_data.table.propsDictionary[i].tween..")"
				elseif MEM.art_data.table.propsDictionary[i].dynamic then
					return "Dynamic"
				else
					return "Static"
				end
			end,
			template = "model_dynamic;",
			tint = function(i)
				if (MEM.art_data.table.propsDictionary[i].tween or 0) > 0 then
					return SET.colour_highlight_tween
				elseif MEM.art_data.table.propsDictionary[i].dynamic then
					return SET.colour_highlight_dynamic
				else
					return vmath.vector4(1, 1, 1, 1)
				end
			end,
		},
		{
			type = hash("exclusive_button"),
			node = gui.get_node("model_exclusive/button_white"),
			text_node = gui.get_node("model_exclusive/text"),
			value_fn = function(i)
				if SET.hide_model_count then
					return MEM.art_data.table.propsDictionary[i].key
				else
					return "("..MEM.art_data.table.propsDictionary[i].model_data.model_count..")"..MEM.art_data.table.propsDictionary[i].key
				end
			end,
			template = "model_exclusive;",
			fn = evaluate_button,
			tint = function(i)
				if MEM.art_data.table.propsDictionary[i].hide then
					return SET.colour_hidden_model
				elseif (MEM.art_data.table.propsDictionary[i].tween or 0) > 0 then
					return SET.colour_highlight_tween
				elseif MEM.art_data.table.propsDictionary[i].dynamic then
					return SET.colour_highlight_dynamic
				else
					return vmath.vector4(1, 1, 1, 1)
				end
			end,
		},
		item_count = 0,
		scroll_prefix = "model_"
	}
	model_list = UI.create_list(TAB_NAME, gui.get_node("model_list"), model_list_tab)
	local part_list_tab = {
		{
			type = hash("exclusive_button"),
			node = gui.get_node("part_exclusive/button_white"),
			text_node = gui.get_node("part_exclusive/text"),
			value_fn = function(i)
				if get_selected_model() > 0 then
					return MEM.art_data.table.propsDictionary[get_selected_model()].model_data.parts[i].name
				end
			end,
			template = "part_exclusive;",
			fn = evaluate_button
		},
		item_count = 0,
		scroll_prefix = "part_"
	}
	part_list = UI.create_list(TAB_NAME, gui.get_node("part_list"), part_list_tab)
end

local function update_materials()
	local selected_model = get_selected_model()
	if selected_model > 0 then
		local selected_part = get_selected_part()
		if selected_part == 0 then
			UI.select_exclusive_button(TAB_NAME, part_list, 1)
			selected_part = 1
		end
		local part_tab = MEM.art_data.table.propsDictionary[selected_model].model_data.parts[selected_part]
		if not part_tab then
			G.update_navbar("Cannot render model "..MEM.art_data.table.propsDictionary[selected_model].key)
			return
		end
		local part_material = part_tab.tab[part_tab.index]
		local material_index
		for key, val in ipairs(material_list) do
			if val == part_material then
				material_index = key
				break
			end
		end
		if current_material and not (current_material == material_index) then
			gui.animate(material_buttons[current_material], "color", vmath.vector4(1, 1, 1, 1), gui.EASING_LINEAR, 0.1)
			current_material = nil
		end
		if material_index then
			gui.animate(material_buttons[material_index], "color", SET.colour_highlight_material, gui.EASING_LINEAR, 0.1)
			current_material = material_index
		else
			G.update_navbar("Unknown material on currently seletcted model part")
			current_material = nil
		end
	elseif current_material then
		gui.animate(material_buttons[current_material], "color", vmath.vector4(1, 1, 1, 1), gui.EASING_LINEAR, 0.1)
		current_material = nil
	end
end

local function update_lists()
	UI.update_list(TAB_NAME, model_list, #MEM.art_data.table.propsDictionary)
	if get_selected_model() > 0 then
		local part_table = MEM.art_data.table.propsDictionary[get_selected_model()].model_data.parts
		UI.update_list(TAB_NAME, part_list, #part_table)
		update_materials()
	end
end

local function open_dialog(dialog, message_tab)
	DIALOG.open(TAB_NAME, dialog, message_tab)
	msg.post("/model_viewer", hash("disable_input"))
end

local function import_models()
	local model_data, meta_data
	local num, path = diags.open("zip,pw_art,obj", SET.default_path_import_models)
	if path then
		local f = io.open(path, "rb")
		if f then
			local ext = string.sub(path, -3)
			if ext == "zip" then
				local zip_data = f:read("*a")
				local archive = zip.open(zip_data)
				local file_index = zip.get_number_of_entries(archive) - 1
				local art_found, meta_found
				for i = 0, file_index do
					local file = zip.extract_by_index(archive, i)
					if (not art_found) and string.sub(file.name, -7) == ".pw_art" then
						model_data = file.content
						art_found = true
						if meta_found then break end
					elseif (not meta_found) and string.sub(file.name, -10) == ".geomancer" then
						meta_data = file.content
						meta_found = true
						if art_found then break end
					end
				end
			elseif ext == "obj" then
				local emanelif = string.reverse(path)
				local extension_index = string.find(emanelif, "%.")
				local start_index = string.find(emanelif, "\\")
				local filename = string.reverse(string.sub(emanelif, extension_index + 1, start_index - 1))
				local ok, res = pcall(MEM.parse_obj, f, filename)
				if not ok then 
					G.update_navbar("Error reading "..filename..". Try reexporting it in Blender.")
					io.close(f)
					return
				elseif res then
					io.close(f)
					return
				end
				update_lists()
				model_data = false
				G.update_navbar("Model "..filename.." added.", true)
				UI.select_exclusive_button(TAB_NAME, model_list, #MEM.art_data.table.propsDictionary, false, true)
				select_model(#MEM.art_data.table.propsDictionary)
			else
				model_data = f:read("*a")
				local htap = string.reverse(path)
				local start_index = string.find(htap, "\\")
				local path_no_file = string.reverse(string.sub(htap, start_index + 1))
				for i in lfs.dir(path_no_file) do
					if string.sub(i, -10) == ".geomancer" then
						io.close(f)
						f = io.open(path_no_file.."\\"..i, "rb")
						if f then
							meta_data = f:read("*a")
						end
						break
					end
				end
			end
		end
		io.close(f)
	end
	if model_data then
		model_data = MEM.parse_json(model_data)
		if MEM.check(model_data, "pw_art", "Selected pw_art file") then
			model_data = model_data.propsDictionary
			if model_data[1] and model_data[1].object.name == "Placeholder" then
				table.remove(model_data, 1)
			end
			if #model_data < 1 then
				G.update_navbar("No models found.")
			else
				if meta_data then
					MEM.load_geomancer_data(meta_data, "meta data")
				end
				MEM.art_data.models_for_import = model_data
				open_dialog("dialog_import")
			end
		else
			G.update_navbar("Error reading model data.", true)
		end
	elseif not (model_data == false) then
		G.update_navbar("Error reading model data.", true)
	end
end

local function count_model_instances(model_name)
	local count = 0
	for key, val in ipairs(MEM.art_data.table.staticProps or {}) do
		if val.name == model_name then
			count = count + 1
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicProps or {}) do
		if val.name == model_name then
			count = count + 1
		end
	end
	for key, val in ipairs(MEM.art_data.table.staticCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == model_name then
				count = count + 1
			end
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == model_name then
				count = count + 1
			end
		end
	end
	return count
end

local function model_replace(selected_model_index, replace_model_index)
	local old_name = MEM.art_data.table.propsDictionary[selected_model_index].key
	local new_name = MEM.art_data.table.propsDictionary[replace_model_index].key
	for key, val in ipairs(MEM.art_data.table.staticProps or {}) do
		if val.name == new_name then
			val.name = old_name
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicProps or {}) do
		if val.name == new_name then
			val.name = old_name
		end
	end
	for key, val in ipairs(MEM.art_data.table.staticCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == new_name then
				v.name = old_name
			end
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == new_name then
				v.name = old_name
			end
		end
	end
	for key, val in ipairs(MEM.art_data.table.propsDictionary[selected_model_index].model_data.parts) do
		local new_model_part_tab = MEM.art_data.table.propsDictionary[replace_model_index].model_data.parts[key]
		if new_model_part_tab and new_model_part_tab.name == val.name then
			new_model_part_tab.tab = val.tab
			new_model_part_tab.index = val.index
		end
	end
	MEM.art_data.table.propsDictionary[replace_model_index].key = MEM.art_data.table.propsDictionary[selected_model_index].key
	MEM.art_data.table.propsDictionary[replace_model_index].object.name = MEM.art_data.table.propsDictionary[selected_model_index].object.name
	MEM.art_data.table.propsDictionary[replace_model_index].dynamic = MEM.art_data.table.propsDictionary[selected_model_index].dynamic
	-- something about tweens too

	MEM.art_data.table.propsDictionary[selected_model_index] = MEM.art_data.table.propsDictionary[replace_model_index]
	table.remove(MEM.art_data.table.propsDictionary, replace_model_index)

	local new_index = selected_model_index
	if not (MEM.art_data.table.propsDictionary[selected_model_index] and MEM.art_data.table.propsDictionary[selected_model_index].key == old_name) then
		new_index = new_index - 1
	end
	MEM.art_data.table.propsDictionary[new_index].model_data.model_count = count_model_instances(old_name)

	MEM.create_prop_list(MEM.art_data.table, true)
	MEM.setup_culling_ranges()
	
	msg.post("/model_viewer", hash("update_model"), {model = new_index})
	update_lists()
	UI.select_exclusive_button(TAB_NAME, model_list, new_index)

	G.update_navbar("All instances of "..old_name.." have been replaced by "..new_name.." keeping the original model name and properties.", true)
end

local function rename_model(new_name, model_to_rename)
	local old_name = MEM.art_data.table.propsDictionary[model_to_rename].key
	MEM.art_data.table.propsDictionary[model_to_rename].key = new_name
	MEM.art_data.table.propsDictionary[model_to_rename].object.name = new_name
	
	for key, val in ipairs(MEM.art_data.table.staticProps or {}) do
		if val.name == old_name then
			val.name = new_name
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicProps or {}) do
		if val.name == old_name then
			val.name = new_name
		end
	end
	for key, val in ipairs(MEM.art_data.table.staticCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == old_name then
				v.name = new_name
			end
		end
	end
	for key, val in ipairs(MEM.art_data.table.dynamicCullingRanges or {}) do
		for k, v in ipairs(val.members) do
			if v.name == old_name then
				v.name = new_name
			end
		end
	end
	G.update_navbar(old_name.." renamed to "..new_name, true)
end

local function set_model_as_dynamic(key, value)
	local model_tab = MEM.art_data.table.propsDictionary[key]
	if (model_tab.tween or 0) > 0 then
		value = true
	elseif value == nil then
		value = not model_tab.dynamic
	end
	model_tab.dynamic = value
	return value
end

local function sort_models()
	local selected_model_name
	local selected_model = get_selected_model()
	if selected_model > 0 then
		selected_model_name = MEM.art_data.table.propsDictionary[selected_model].key
	end
	table.sort(MEM.art_data.table.propsDictionary, function(a, b) return string.lower(a.key) < string.lower(b.key) end)
	if selected_model_name then
		for key, val in ipairs(MEM.art_data.table.propsDictionary) do
			if val.key == selected_model_name then
				selected_model = key
				UI.update_list(TAB_NAME, model_list)
				UI.select_exclusive_button(TAB_NAME, model_list, selected_model)
			end
		end
	else
		UI.update_list(TAB_NAME, model_list)
	end
	MEM.create_prop_list(MEM.art_data.table, true)
	MEM.setup_culling_ranges()
	G.update_navbar("Models sorted alphabetically", true)
end

local function delete_model(model) -- breaks maps, do not use without modifying pw_meta as well
	local model_name = MEM.art_data.model_list[model].name
	table.remove(MEM.art_data.model_list, model)
	for key = #MEM.art_data.table_static_props, 1, -1 do
		if MEM.art_data.table_static_props[key].name == model_name then
			table.remove(MEM.art_data.table_static_props[key])
		end
	end
	for key = #MEM.art_data.table_dynamic_props, 1, -1 do
		if MEM.art_data.table_dynamic_props[key].name == model_name then
			table.remove(MEM.art_data.table_dynamic_props[key])
		end
	end
	for key = #MEM.art_data.table_culling_ranges, 1, -1 do
		for k = #MEM.art_data.table_culling_ranges[key].members, 1, -1 do
			if MEM.art_data.table_culling_ranges[key].members[k].name == model_name then
				table.remove(MEM.art_data.table_culling_ranges[key].members, k)
			end
		end
		if #MEM.art_data.table_culling_ranges[key].members < 1 then
			table.remove(MEM.art_data.table_culling_ranges, key)
		end
	end
	for key = #MEM.art_data.table_dynamic_culling_ranges, 1, -1 do
		for k = #MEM.art_data.table_dynamic_culling_ranges[key].members, 1, -1 do
			if MEM.art_data.table_dynamic_culling_ranges[key].members[k].name == model_name then
				table.remove(MEM.art_data.table_dynamic_culling_ranges[key].members, k)
			end
		end
		if #MEM.art_data.table_dynamic_culling_ranges[key].members < 1 then
			table.remove(MEM.art_data.table_dynamic_culling_ranges, key)
		end
	end
	MEM.art_data.mesh_list[model_name] = nil
	update_lists()
	G.update_navbar("All instances of "..model_name.." deleted.", true)
end

local function change_model_material(model_index, part_index, material, change_all)
	if change_all then
		for key, val in ipairs(MEM.art_data.table.propsDictionary[model_index].model_data.parts) do
			if not val.collider then
				val.tab[val.index] = material
				val.tab._pure_array = nil
			end
		end
	else
		local part_tab = MEM.art_data.table.propsDictionary[model_index].model_data.parts[part_index]
		part_tab.tab[part_tab.index] = material
		part_tab.tab._pure_array = nil
	end
end

local function degeomance()
	local tween_count, dynamic_count, material_count = 0, 0, 0
	for key, val in ipairs(MEM.art_data.table.propsDictionary) do
		if val.tween then
			local function remove_tweens(tab)
				for i = #tab.components, 1, -1 do
					if tab.components[i].type == "LevelEventReceiver" or tab.components[i].type == "ScriptedTween" then
						table.remove(tab.components, i)
					end
				end
				if tab.children then
					for k, v in ipairs(tab.children) do
						remove_tweens(v)
					end
				end
			end
			remove_tweens(val.object)
			for k, v in ipairs(val.model_data.transform_list) do
				v.tween = nil
			end
			tween_count = tween_count + val.tween
			val.tween = 0
		end
		if val.dynamic then
			set_model_as_dynamic(key, false)
			dynamic_count = dynamic_count + 1
		end
		local safe_mats = {["(DoNotEdit)LiveMat_Props"] = true, ["(DoNotEdit)LiveMat_LevelGeoSimple"] = true,
		["(DoNotEdit)LiveMat_Glow"] = true, ["(DoNotEdit)LiveMat_GlowInvert"] = true}

		for k, v in ipairs(val.model_data.parts) do
			if not safe_mats[v.tab[v.index]] then
				change_model_material(key, k, "(DoNotEdit)LiveMat_Props")
				material_count = material_count + 1
			end
		end
	end
	local change = false
	if tween_count > 1 then
		G.update_navbar("Removed "..tween_count.." tweens")
		change = true
	elseif tween_count > 0 then
		G.update_navbar("Removed one tween")
		change = true
	end
	if dynamic_count > 1 then
		G.update_navbar(dynamic_count.." models set as static")
		change = true
	elseif dynamic_count > 0 then
		G.update_navbar("One model set as static")
		change = true
	end
	if material_count > 1 then
		G.update_navbar("Changed "..material_count.." materials")
		change = true
	elseif material_count > 0 then
		G.update_navbar("Changed one material")
		change = true
	end
	if not change then
		G.update_navbar("No model changes necessary")
	end
end

local function check_tweens()
	local selected_model = get_selected_model()
	if selected_model then
		local model_tab = MEM.art_data.table.propsDictionary[selected_model]
		if not model_tab then
			UI.update_list(TAB_NAME, model_list, 0)
			return
		end
		model_tab.tween = 0
		if model_tab.model_data.tween_list then
			model_tab.tween = #model_tab.model_data.tween_list
		end
		if model_tab.tween > 0 then
			set_model_as_dynamic(selected_model, true)
		else
			set_model_as_dynamic(selected_model, false)
		end
		UI.update_list(TAB_NAME, model_list, #MEM.art_data.table.propsDictionary)
	end
end

local function change_tab(new_tab)
	new_tab = new_tab or current_tab
	gui.set_color(tab_buttons[current_tab], vmath.vector4(1))
	gui.set_color(tab_buttons[new_tab], SET.colour_active_text_field)
	if current_tab == "button_materials" then
		gui.set_enabled(gui.get_node("materials_background"), false)
		UI.unload_template(TAB_NAME, "colour_guide")
	elseif current_tab == "button_transforms" then
		gui.set_enabled(gui.get_node("transforms_background"), false)
		UI.unload_template(TAB_NAME, {"transform_add", "transform_delete", "transform_parent", "transform_rename"})
		UI.disable_list(TAB_NAME, transform_ui_list)
	elseif current_tab == "button_tweens" then
		gui.set_enabled(gui.get_node("tweens_background"), false)
		UI.disable_list(TAB_NAME, tween_ui_list)
		UI.unload_template(TAB_NAME, {"tween_add", "tween_edit", "tween_rename", "tween_delete", "tween_preview"})
	elseif current_tab == "button_instances" then
		gui.set_enabled(gui.get_node("instances_background"), false)
		UI.disable_list(TAB_NAME, instance_ui_list)
	end
	current_tab = new_tab
	local selected_model = get_selected_model()
	if MEM.art_data.table.propsDictionary[selected_model].model_data.do_not_render then
		return
	end
	if current_tab == "button_materials" then
		gui.set_enabled(gui.get_node("materials_background"), true)
		UI.load_template("colour_guide", TAB_NAME)
	elseif current_tab == "button_transforms" then
		gui.set_enabled(gui.get_node("transforms_background"), true)
		UI.load_template({"transform_add", "transform_delete", "transform_parent", "transform_rename"}, TAB_NAME)
		TRANS.show(get_selected_model())
		UI.enable_list(TAB_NAME, transform_ui_list)
	elseif current_tab == "button_tweens" then
		gui.set_enabled(gui.get_node("tweens_background"), true)
		UI.enable_list(TAB_NAME, tween_ui_list)
		UI.load_template({"tween_add", "tween_edit", "tween_rename", "tween_delete", "tween_preview"}, TAB_NAME)
	elseif current_tab == "button_instances" then
		gui.set_enabled(gui.get_node("instances_background"), true)
		UI.enable_list(TAB_NAME, instance_ui_list)
	end
end

local function select_tween(new_selection)
	new_selection = new_selection or selected_tween
	if new_selection == 0 then
		new_selection = 1
	end
	local tween_count = #tween_list
	if new_selection > tween_count then
		new_selection = tween_count
	end
	selected_tween = new_selection
	UI.select_exclusive_button(TAB_NAME, tween_ui_list, new_selection, true, true)
end

local function update_prop_instance_list(model_index)
	model_index = model_index or get_selected_model()
	instance_list = {}
	for key, val in ipairs(MEM.art_data.prop_list) do
		if val.model_index == model_index then
			table.insert(instance_list, val)
		end
	end
	UI.update_list(TAB_NAME, instance_ui_list, #instance_list)
end

local function check_tween_collisions()
	local transforms = {}
	for tween_index, val in ipairs(tween_list) do
		val.collision = nil
		for key, action in ipairs(val.script) do
			if action.part then
				transforms[action.part] = transforms[action.part] or {}
				transforms[action.part][action.type] = transforms[action.part][action.type] or {}
				if not transforms[action.part][action.type][tween_index] then
					transforms[action.part][action.type][tween_index] = true
					transforms[action.part][action.type].count = (transforms[action.part][action.type].count or 0) + 1
				end
			end
		end
	end
	for key, v in pairs(transforms) do
		for action_type, val in pairs(v) do
			if val.count > 1 then
				val.count = nil
				for k in pairs(val) do
					tween_list[k].collision = true
				end
			end
		end
	end
end

local function sort_tweens()
	local selected_name
	if selected_tween > #tween_list then selected_tween = #tween_list end
	if selected_tween > 0 then
		selected_name = tween_list[selected_tween].name
	end
	table.sort(tween_list, function(a, b) return string.lower(a.name) < string.lower(b.name) end)
	if selected_name then
		for key, val in ipairs(tween_list) do
			if val.name == selected_name then
				select_tween(key)
				break
			end
		end
	end
	check_tween_collisions()
	UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
end

function select_model(selected_model)
	selected_model = selected_model or get_selected_model()
	UI.update_list(TAB_NAME, part_list, #MEM.art_data.table.propsDictionary[selected_model].model_data.parts)
	UI.select_exclusive_button(TAB_NAME, part_list, 1)
	tween_list = MEM.art_data.table.propsDictionary[selected_model].model_data.tween_list
	UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
	if #tween_list > 0 then
		sort_tweens()
	end
	update_prop_instance_list(selected_model)
	change_tab()
	if MEM.art_data.table.propsDictionary[selected_model].model_data.do_not_render then
		msg.post("/model_viewer", hash("remove_model"))
		TRANS.invalid_model()
		return
	end
	TRANS.load_model_data(selected_model)
	UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
	select_tween()
	update_materials()
	msg.post("/model_viewer", hash("update_model"), {model = selected_model, selected_part = 1})
end

local function delete_tween()
	table.remove(tween_list, selected_tween)
	check_tweens()
	if selected_tween > #tween_list then selected_tween = #tween_list end
	UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
	select_tween()
	G.update_navbar("Tween deleted", true)
end

local function remove_prop(item, hold_off_clean_up)
	local function clean_up()
		if hold_off_clean_up then return end
		local model_index = get_selected_model()
		table.remove(instance_list, item)
		MEM.art_data.table.propsDictionary[model_index].model_data.model_count = MEM.art_data.table.propsDictionary[model_index].model_data.model_count - 1
		MEM.create_prop_list(MEM.art_data.table, true)
		MEM.setup_culling_ranges()
		update_prop_instance_list(model_index)
		update_lists()
		G.update_navbar("Prop instance deleted", true)
	end
	local prop_tab = instance_list[item].prop_tab
	for k, v in ipairs(MEM.art_data.table.staticProps or {}) do
		if v == prop_tab then
			table.remove(MEM.art_data.table.staticProps, k)
			clean_up()
			return
		end
	end
	for k, v in ipairs(MEM.art_data.table.dynamicProps or {}) do
		if v == prop_tab then
			table.remove(MEM.art_data.table.dynamicProps, k)
			clean_up()
			return
		end
	end
	for k, v in ipairs(MEM.art_data.table.staticCullingRanges or {}) do
		for _k, _v in ipairs(v.members) do
			if _v == prop_tab then
				table.remove(v.members, _k)
				if #v.members < 1 then
					table.remove(MEM.art_data.table.staticCullingRanges, k)
				end
				clean_up()
				return
			end
		end
	end
	for k, v in ipairs(MEM.art_data.table.dynamicCullingRanges or {}) do
		for _k, _v in ipairs(v.members) do
			if _v == prop_tab then
				table.remove(v.members, _k)
				if #v.members < 1 then
					table.remove(MEM.art_data.table.dynamicCullingRanges, k)
				end
				clean_up()
				return
			end
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("hide") then
		msg.post("#", hash("disable"))
		msg.post("#", hash("release_input_focus"))
		DIALOG.close_all(TAB_NAME)
		msg.post(UI.tab.dialog_tween.path, hash("hide"))
		msg.post("/model_viewer", hash("hide"))
	elseif message_id == hash("show") then
		msg.post("#", hash("enable"))
		msg.post("#", hash("acquire_input_focus"))
		local model_for_viewer
		update_lists()
		if #MEM.art_data.table.propsDictionary > 0 then
			local selected_model = get_selected_model()
			if get_selected_model() < 1 then
				selected_model = 1
			end
			UI.select_exclusive_button(TAB_NAME, model_list, selected_model, true)
			tween_list = MEM.art_data.table.propsDictionary[selected_model].model_data.tween_list
			sort_tweens()
			UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
			model_for_viewer = selected_model
			if MEM.art_data.table.propsDictionary[selected_model].model_data.do_not_render then
				msg.post("/model_viewer", hash("remove_model"))
				TRANS.invalid_model()
			else
				TRANS.load_model_data(selected_model)
			end
			update_prop_instance_list(selected_model)
			update_lists()
		end
		msg.post("/model_viewer", hash("show_model_preview"), {model = model_for_viewer or get_selected_model(), selected_part = get_selected_part()})
		msg.post("/model_viewer", hash("set_ui"), {mode = hash("model")})
	elseif message_id == hash("reset") then
		UI.update_list(TAB_NAME, model_list, 0)
		UI.update_list(TAB_NAME, part_list, 0)
		UI.scroll_to_item(TAB_NAME, model_list, 0)
		UI.scroll_to_item(TAB_NAME, part_list, 0)
		update_materials()
		msg.post("/model_viewer", hash("remove_model"))
	elseif message_id == hash("check_tweens") then
		check_tweens()
	elseif message_id == hash("dialog_closed") then
		msg.post("#", hash("acquire_input_focus"))
		msg.post("/model_viewer", hash("show"))
		if message.dialog == "dialog_import" then
			if message.import then
				local model_count = 0
				local dictionary_length = #MEM.art_data.table.propsDictionary
				for key, val in ipairs(MEM.art_data.models_for_import) do
					if not MEM.art_data.models_for_import_ignore[val.key] then
						MEM.add_metadata(val)
						val.model_data.model_count = 0
						table.insert(MEM.art_data.table.propsDictionary, val)
						model_count = model_count + 1
					end
				end
				MEM.check_metadata_for_tween_scripts(dictionary_length + 1)
				if model_count < 1 then
					G.update_navbar("No models added.", true)
				elseif model_count == 1 then
					G.update_navbar("Imported one model.", true)
					update_lists()
				else
					G.update_navbar("Imported "..model_count.." models.", true)
					update_lists()
				end
			else
				G.update_navbar("No models added.", true)
			end
			MEM.art_data.models_for_import = nil
			MEM.art_data.models_for_import_ignore = nil
		elseif message.dialog == "dialog_replace_model" then
			if message.selected_model then
				model_replace(message.model_to_replace, message.selected_model)
			end
		elseif message.dialog == "dialog_rename_model" then
			if message.new_name then
				rename_model(message.new_name, message.model_to_rename)
				update_lists()
			end
		elseif message.dialog == "dialog_transform" then
			msg.post(".", hash("enable"))
			update_lists()
			check_tweens()
			msg.post("/model_viewer", hash("show"), {model = get_selected_model()})
			msg.post("/model_viewer", hash("show_part"), {selected_part = get_selected_part()})
		elseif message.dialog == "dialog_parent_transform" and message.new_parent then
			TRANS.new_parent(message.new_parent)
		elseif message.dialog == "dialog_confirm" then
			if message.subject == "delete_transform" and message.button == 1 then
				TRANS.delete_transform()
			elseif message.subject == "delete_model" then
				if message.button == 1 then	-- 1 is delete, 3 is cancel
					delete_model(get_selected_model())
				elseif message.button == 3 then
					G.update_navbar("Model deletion canceled", true)
				end
			elseif message.subject == hash("delete_tween") then
				if message.button == 1 then -- 1 is delete, 3 is cancel
					delete_tween()
				elseif message.button == 3 then
					G.update_navbar("Tween deletion canceled", true)
				end
			else
				local div = string.find(message.subject, ";")
				if div then
					if string.sub(message.subject, 1, div - 1) == "delete_prop" then
						if message.button == 1 then -- 1 is delete, 3 is cancel
							remove_prop(tonumber(string.sub(message.subject, div + 1)))
						else
							G.update_navbar("Prop deletion cancelled", true)
						end
					end
				end
			end
		elseif message.dialog == "dialog_get_text" then
			if message.subject == "rename_transform" and message.text then
				if message.text == "Colliders" then
					G.update_navbar("The name \"Colliders\" is reserved for collider data (not supported by custom maps). Choose a different name", true)
				elseif message.text == SET.tween_parent_transform_name then
					G.update_navbar("The name "..SET.tween_parent_transform_name.." is reserved by Geomancer. Choose a different name", true)
				else
					TRANS.rename_transform(message.text)
				end
			elseif message.subject == "new_transform" or message.subject == "new_transform_parent" then
				if message.text then
					TRANS.add_transform(message.text, nil, message.subject == "new_transform_parent")
				else
					G.update_navbar("Transform not added", true)
				end
			elseif message.subject == hash("tween_rename") then
				if message.text then
					for key, val in ipairs(tween_list) do
						if val.name == message.text then
							if key == selected_tween then
								G.update_navbar("Tween name unchanged", true)
								return
							else
								G.update_navbar("Name already exists. Pick a different one", true)
								return
							end
						end
					end
					tween_list[selected_tween].name = message.text
					G.update_navbar("Tween renamed", true)
					sort_tweens()
				end
			end
		elseif message.dialog == "dialog_find" then
			if message.selected_model then
				UI.select_exclusive_button(TAB_NAME, model_list, message.selected_model)
				select_model(message.selected_model)
			end
		elseif message.dialog == "dialog_instance_list" then
			if message.prop_index then
				local instance_index
				for key, val in ipairs(instance_list) do
					if val.prop_list_index == message.prop_index then
						instance_index = key
						break
					end
				end
				instance_index = instance_index + message.next
				if instance_index > #instance_list then
					instance_index = 1
				elseif instance_index < 1 then
					instance_index = #instance_list
				end
				open_dialog("dialog_instance_list", {model_index = get_selected_model(), prop_index = instance_list[instance_index].prop_list_index})
			else
				MEM.create_prop_list(MEM.art_data.table, true)
				MEM.setup_culling_ranges()
				update_prop_instance_list(get_selected_model())
				UI.update_list(TAB_NAME, model_list, #MEM.art_data.table.propsDictionary)
			end
		elseif message.dialog == "dialog_tween" then
			if SET.delete_empty_tweens and #tween_list[selected_tween].script < 1 then
				delete_tween()
			else
				check_tween_collisions()
				UI.update_list(TAB_NAME, tween_ui_list, #tween_list)
			end
			select_tween()
		elseif message.dialog == "dialog_create_geo" then
			if message.changes then
				if SET.scale_prop_after_geo then
					if SET.generate_geo_for_all_instances then
						for key, val in ipairs(instance_list) do
							val.scale = vmath.vector3(0, 0, 0)
							val.prop_tab.scale = "0,0,0"
						end
					else
						instance_list[message.prop_index].scale = vmath.vector3(0, 0, 0)
						instance_list[message.prop_index].prop_tab.scale = "0,0,0"
					end
				elseif SET.delete_prop_after_geo then
					local model_index = get_selected_model()
					if SET.generate_geo_for_all_instances then
						MEM.art_data.table.propsDictionary[model_index].model_data.model_count = 1
						for key, val in ipairs(instance_list) do
							remove_prop(key, key < #instance_list)
						end
					else
						remove_prop(message.prop_index.prop_tab)
					end
					MEM.create_prop_list(MEM.art_data.table, true)
					MEM.setup_culling_ranges()
					update_prop_instance_list(model_index)
					update_lists()
				end
			end
		end
	elseif message_id == hash("degeomance") then
		degeomance()
	end
end

local function open_tween_editor(tween_id)
	tween_id = tween_id or selected_tween
	if tween_id > 0 then
		msg.post("/art#tab_art", hash("check_tweens"))
		msg.post("/model_viewer", hash("stop_flashing"))
		open_dialog("dialog_tween", {model_index = get_selected_model(), tween_index = tween_id})
	else
		G.update_navbar("Select a tween first", true)
	end
end

function evaluate_button(button, item)
	if button == "sort" then
		sort_models()
	elseif button == "import_models" then
		import_models()
	elseif button == "import_models_bulk" then
		local _, path = diags.open_folder(SET.default_path_import_models)
		local file_list = {}
		for filename in lfs.dir(path) do
			if string.sub(filename, -4) == ".obj" then
				table.insert(file_list, {path = path.."\\"..filename, name = string.sub(filename, 1, -5)})
			end
		end

		local error_count, import_count = 0, 0
		local function import_obj(file_data)
			local f = io.open(file_data.path, "rb")
			if f then
				local ok, res = pcall(MEM.parse_obj, f, file_data.name)
				if (not ok) or res then
					error_count = error_count + 1
				else
					import_count = import_count + 1
				end
				io.close(f)
			else
				error_count = error_count + 1
			end
		end
		
		for key, val in ipairs(file_list) do
			import_obj(val)
		end

		if import_count > 0 then
			update_lists()
			UI.select_exclusive_button(TAB_NAME, model_list, #MEM.art_data.table.propsDictionary, false, true)
			select_model(#MEM.art_data.table.propsDictionary)
			if import_count > 1 then
				G.update_navbar(import_count.." models imported.")
			else
				G.update_navbar("One model imported.")
			end
		end
		if error_count > 1 then
			G.update_navbar(error_count.." models failed to import.")
		elseif error_count > 0 then
			G.update_navbar("One model failed to import.")
		end
		if import_count + error_count < 1 then
			G.update_navbar("No model files found.")
		end
	elseif button == "colour_guide" then
		sys.open_url("https://mod.io/g/pistol-whip/r/advanced-color-hack-guide")
	elseif button == "button_replace" then
		local selected_model = get_selected_model()
		if selected_model > 0 then
			open_dialog("dialog_replace_model", {model_to_replace = selected_model})
		else
			G.update_navbar("Select a model first", true)
		end
	elseif button == "button_rename" then
		local selected_model = get_selected_model()
		if selected_model > 0 then
			open_dialog("dialog_rename_model", {model_to_rename = selected_model})
		else
			G.update_navbar("Select a model first", true)
		end
	elseif button == "button_find" then
		open_dialog("dialog_find")
	elseif button == "button_delete" then
		local selected_model = get_selected_model()
		if selected_model > 0 then
			local model_name = MEM.art_data.model_list[selected_model].name
			local instance_count = count_model_instances(model_name)
			local dialog_title
			if instance_count < 1 then
				dialog_title = "Delete model "..model_name.."?\nThere are no instances in the map."
			elseif instance_count > 1 then
				dialog_title = "Delete model "..model_name.."?\nThere are "..instance_count.." instances in the map."
			else
				dialog_title = "Delete model "..model_name.."?\nThere is one instance in the map."
			end
			open_dialog("dialog_confirm", {title = dialog_title, button_1 = "Delete", button_3 = "Cancel", subject = "delete_model"})
		else
			G.update_navbar("Select a model to delete first", true)
		end
	elseif button == "materials" then
		local selected_model = get_selected_model()
		if selected_model > 0 then
			local selected_part = get_selected_part()
			if MEM.art_data.table.propsDictionary[selected_model].model_data.parts[selected_part].collider then
				G.update_navbar("Cannot change the material of a collider mesh", true)
			else
				if UI.shift_held then
					change_model_material(selected_model, selected_part, material_list[item], true)
					msg.post("/model_viewer", hash("change_material"), {model_index = selected_model})
				else
					change_model_material(selected_model, selected_part, material_list[item])
					msg.post("/model_viewer", hash("change_material"), {part_index = selected_part, model_index = selected_model})
				end
				update_materials()
			end
		else
			G.update_navbar("Select a model and one of its parts first.", true)
		end
	elseif button == "transform_delete" then
		TRANS.delete_transform_clicked()
	elseif button == "transform_rename" then
		TRANS.rename_clicked()
	elseif button == "transform_parent" then
		TRANS.parent_clicked()
	elseif button == "transform_add" then
		TRANS.add_clicked()
	elseif button == "tween_add" then
		check_tweens()
		msg.post("/model_viewer", hash("stop_flashing"))
		local selected_model = get_selected_model()
		local existing_names = {}
		for key, val in ipairs(MEM.art_data.table.propsDictionary[selected_model].model_data.transform_list) do
			existing_names[val.name] = true
		end
		for key, val in ipairs(tween_list) do
			existing_names[val.name] = true
		end
		local new_name
		for i = 1, 99999 do
			new_name = "Tween_"..i
			if not existing_names[new_name] then
				break
			end
		end
		table.insert(tween_list, {signal = "tween", script = {}, name = new_name})
		select_tween(#tween_list)
		sort_tweens()
		open_dialog("dialog_tween", {model_index = selected_model, tween_index = selected_tween})
	elseif button == "tween_edit" then
		open_tween_editor()
	elseif button == "tween_rename" then
		if selected_tween > 0 then
			open_dialog("dialog_get_text", {subject = hash("tween_rename"), default_text = tween_list[selected_tween].name, title = "Enter a new name"})
		else
			G.update_navbar("Select a tween first", true)
		end
	elseif button == "tween_delete" then
		if selected_tween > 0 then
			if SET.confirm_tween_deletion and #tween_list[selected_tween].script > 0 then
				local dialog_title = "Delete tween "..tween_list[selected_tween].name.."?"
				open_dialog("dialog_confirm", {title = dialog_title, button_1 = "Delete", button_3 = "Cancel", subject = hash("delete_tween")})
			else
				delete_tween()
			end
		else
			G.update_navbar("Select a tween first", true)
		end
	elseif button == "tween_preview" then
		if selected_tween > 0 then
			if #tween_list[selected_tween].script < 1 then
				G.update_navbar("Tween has no actions", true)
			else
				local tween_viable
				for key, val in ipairs(tween_list[selected_tween].script) do
					if not (val.type == "X" or val.type == "W") then
						tween_viable = true
						break
					end
				end
				if tween_viable then
					msg.post("#", hash("disable"))
					msg.post("#", hash("release_input_focus"))
					msg.post("/model_viewer", hash("show_preview"), {source = hash("model_tab"), model = get_selected_model(), tween_index = selected_tween})
				else
					G.update_navbar("Tween has no previewable actions", true)
				end
			end
		else
			G.update_navbar("Select a tween first", true)
		end
	elseif button == "button_materials" then
		change_tab(button)
	elseif button == "button_transforms" then
		change_tab(button)
	elseif button == "button_tweens" then
		change_tab(button)
	elseif button == "button_instances" then
		change_tab(button)
	elseif button == model_list then
		select_model()
	elseif button == part_list then
		msg.post("/model_viewer", hash("show_part"), {selected_part = item or 1})
		update_materials()
	elseif button == transform_ui_list then
		TRANS.transform_selected(item)
	elseif button == tween_ui_list then
		if item == selected_tween then
			open_tween_editor()
		else
			select_tween(item)
		end
	else
		local div = string.find(button, ";")
		local str = string.sub(button, 1, div)
		if str == "model_dynamic;" then
			if (MEM.art_data.table.propsDictionary[item].tween or 0) > 0 then
				UI.select_exclusive_button(TAB_NAME, model_list, item)
				select_model(item)
				change_tab("button_tweens")
			else
				set_model_as_dynamic(item)
			end
			UI.update_list(TAB_NAME, model_list)
		elseif str == "model_hide;" then
			MEM.art_data.table.propsDictionary[item].hide = not MEM.art_data.table.propsDictionary[item].hide
			UI.update_list(TAB_NAME, model_list)
		elseif str == "instance_edit;" then
			open_dialog("dialog_instance_list", {model_index = get_selected_model(), prop_index = instance_list[item].prop_list_index})
		elseif str == "geo;" then
			open_dialog("dialog_create_geo", {model_index = get_selected_model(), prop_index = item})
		elseif str == "prop_view;" then
			MEM.setup_culling_ranges()
			MOD.find_prop = vmath.vector3(instance_list[item].position.x, instance_list[item].position.y, 0)
			msg.post("#", hash("disable"))
			msg.post("#", hash("release_input_focus"))
			local pos = instance_list[item].position.z / 3
			msg.post("/model_viewer", hash("show_preview"), {
				source = hash("model_tab"), jump_to = pos, preview_map = true
			})
		elseif str == "prop_delete;" then
			if SET.ask_before_deleting_prop then
				local title = "Are you sure you want to delete this prop?"
				open_dialog("dialog_confirm", {title = title, button_1 = "Delete", button_3 = "Cancel", subject = "delete_prop;"..item})
			else
				remove_prop(item)
			end
		end
	end
end

function evaluate_input(field, text)
	if TRANS.controls_list[field] then
		TRANS.evaluate_input(field, text)
	end
end

function update()
	if UI.current_tab == TAB_NAME then
		for list_index in pairs(UI.tab[TAB_NAME].scrolling) do
			UI.move_list_root(TAB_NAME, list_index, true)
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and gui.pick_node(gui.get_node("materials_background"), action.x, action.y) then
		if action.pressed and current_tab == "button_materials" then
			for key, val in ipairs(material_buttons) do
				if gui.pick_node(val, action.x, action.y) then
					evaluate_button("materials", key)
					return
				end
			end
		end
		UI.on_input(TAB_NAME, action_id, action, evaluate_button, evaluate_input)
	else
		UI.on_input(TAB_NAME, action_id, action, evaluate_button, evaluate_input)
	end
end