local UI = require "modules.ui"
local MEM = require "modules.memory"
local SET = require "modules.settings"
local MOD = require "modules.models"
local G = require "modules.global"
local DIALOG = UI.DIALOG
local DIALOG_NAME = "dialog_export_model"
local DIALOG_DATA

local model_index, export_path

function init(self)
	DIALOG.setup(DIALOG_NAME)
	DIALOG_DATA = UI.tab[DIALOG_NAME]
	UI.load_template({"checkbox_export_all", "checkbox_apply_transforms", "change_path", "export", "export_cancel"}, DIALOG_NAME)
end

local function update_buttons()
	local state = {[true] = "X", [false] = ""}
	gui.set_text(gui.get_node("checkbox_export_all/text"), state[SET.export_all_models])
	gui.set_text(gui.get_node("checkbox_apply_transforms/text"), state[SET.apply_transforms_when_exporting])
	gui.set_text(gui.get_node("path_model_export"), export_path)
	if SET.export_all_models then
		gui.set_text(gui.get_node("dialog_export_title"), "Export ALL models as .obj")
	else
		gui.set_text(gui.get_node("dialog_export_title"), "Export "..MEM.art_data.table.propsDictionary[model_index].key.." as .obj")
	end
end

local function export_model(model_tab)
	if model_tab.model_data.do_not_render then
		G.update_navbar("Unable to export "..model_tab.key)
		return
	end
	local path = export_path..model_tab.key..".obj"
	if sys.exists(path) then
		for name_index = 1, 1000 do
			path = export_path..model_tab.key.."_"..name_index..".obj"
			if not sys.exists(path) then
				break
			end
			if name_index > 999 then
				G.update_navbar("Cannot find a free filename for "..model_tab.key, false)
				return
			end
		end
	end
	
	local f = G.safe_output(path)
	if f then
		io.write("# Exported from [mapname] by Geomancer")
		local meshes = {}
		local offset_v, offset_n = 1, 1
		for key, val in ipairs(model_tab.model_data.transform_list) do
			if val.meshes then
				io.write("\no "..val.name)
				local flip = 1
				local transform_matrix
				if SET.apply_transforms_when_exporting then
					local matrix_list = {}
					local function get_transform_list(transform_tab)
						if transform_tab.parent_tab then
							get_transform_list(transform_tab.parent_tab)
							local pos = vmath.vector3(transform_tab.position)
							--pos.x = -pos.x
							table.insert(matrix_list, vmath.matrix4_compose(pos, transform_tab.rotation, transform_tab.scale))
							flip = flip * transform_tab.scale.x * transform_tab.scale.y * transform_tab.scale.z
						end
					end
					get_transform_list(val)
					transform_matrix = vmath.matrix4()
					for k, v in ipairs(matrix_list) do
						transform_matrix = transform_matrix * v
					end
				end
				for mesh_index, mesh_tab in ipairs(val.meshes) do
					if not mesh_tab.verts_parsed then
						MOD.create_mesh(mesh_tab)
					end
					--io.write("\ng "..val.name)
					for k, v in ipairs(mesh_tab.verts_parsed) do
						if transform_matrix then
							local vertex_coords = vmath.vector4(v[1], v[2], v[3], 1)
							local vertex_x = vmath.dot(vertex_coords, vmath.vector4(transform_matrix.m00, transform_matrix.m01, transform_matrix.m02, transform_matrix.m03))
							local vertex_y = vmath.dot(vertex_coords, vmath.vector4(transform_matrix.m10, transform_matrix.m11, transform_matrix.m12, transform_matrix.m13))
							local vertex_z = vmath.dot(vertex_coords, vmath.vector4(transform_matrix.m20, transform_matrix.m21, transform_matrix.m22, transform_matrix.m23))
							io.write("\nv "..vertex_x.." "..vertex_y.." "..vertex_z)
						else
							io.write("\nv "..v[1].." "..v[2].." "..v[3])
						end
					end
					for k, v in ipairs(mesh_tab.normals_parsed) do
						local mod = k % 3
						if mod == 1 then
							io.write("\nvn ")
						end
						io.write(v.." ")
					end
					if SET.apply_transforms_when_exporting then
						for tris_index = 1, #mesh_tab.tris, 3 do
							local tris_1 = mesh_tab.tris[tris_index] + offset_v
							local tris_2, tris_3
							if flip > 0 then
								tris_2 = mesh_tab.tris[tris_index + 1] + offset_v
								tris_3 = mesh_tab.tris[tris_index + 2] + offset_v
							else
								tris_2 = mesh_tab.tris[tris_index + 2] + offset_v
								tris_3 = mesh_tab.tris[tris_index + 1] + offset_v
							end
							io.write("\nf "..tris_1.."//"..tris_1.." ")
							io.write(tris_1.."//"..tris_2.." ")
							io.write(tris_3.."//"..tris_3)
						end
					else
						for k, v in ipairs(mesh_tab.tris) do
							local mod = k % 3
							if mod == 1 then
								io.write("\nf ")
							end
							local i = v + offset_v
							io.write(i.."//"..i.." ")
						end
					end
					offset_v = offset_v + #mesh_tab.verts_parsed
				end
			end
		end
	
		io.close(f)
	end
end

local function evaluate_button(button)
	if button == "export" or button == "enter" then
		if not sys.exists(export_path) then
			local _, path = diags.open_folder()
			if path then
				export_path = path
				gui.set_text(gui.get_node("path_model_export"), export_path)
			else
				G.update_navbar("Export path not valid", true)
				return
			end
		end
		export_path = export_path.."\\"
		if SET.export_all_models then
			for key, val in ipairs(MEM.art_data.table.propsDictionary) do
				export_model(val)
			end
		else
			export_model(MEM.art_data.table.propsDictionary[model_index])
		end
	elseif button == "export_cancel" or button == "escape" then
		DIALOG.close(DIALOG_NAME)
	elseif button == "change_path" then
		local _, path = diags.open_folder(export_path)
		if path then
			export_path = path
			gui.set_text(gui.get_node("path_model_export"), export_path)
		end
	elseif button == "checkbox_export_all" then
		if model_index > 0 then
			SET.export_all_models = not SET.export_all_models
			update_buttons()
		end
	elseif button == "checkbox_apply_transforms" then
		SET.apply_transforms_when_exporting = not SET.apply_transforms_when_exporting
		update_buttons()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
		DIALOG.show(DIALOG_DATA, sender)
		model_index = message.model_index
		local model_name = "all models"
		if model_index > 0 then
			model_name = MEM.art_data.table.propsDictionary[model_index].key
			SET.export_all_models = false
		else
			SET.export_all_models = true
		end
		gui.set_text(gui.get_node("dialog_export_title"), "Export "..model_name.." as .obj")
		export_path = SET.default_path_model_export
		update_buttons()
	end
end

function on_input(self, action_id, action)
	UI.on_input(DIALOG_NAME, action_id, action, evaluate_button)
end