embedded_components {
  id: "transform_model"
  type: "model"
  data: "mesh: \"/assets/models/transform.dae\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/render/other_materials/transform.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/models/transform_tex.png\"\n"
  "  }\n"
  "}\n"
  ""
}
